// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/reminder/data/models/reminder_model.dart';
import 'features/reminder/data/models/reminder_template_model.dart';
import 'features/schedule/data/models/category_model.dart';
import 'features/schedule/data/models/schedule_model.dart';
import 'features/sync/data/models/device_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 263682012878894995),
      name: 'CategoryModel',
      lastPropertyId: const obx_int.IdUid(8, 1433902640238436279),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 970273487234632712),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2216595015002857581),
            name: 'categoryId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 1755180745289735871)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8075488864048884327),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7672130673843261599),
            name: 'color',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3879418617465401681),
            name: 'icon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7287358550133256650),
            name: 'isDefault',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8854458380885681860),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1433902640238436279),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 871680447717514891),
      name: 'DeviceModel',
      lastPropertyId: const obx_int.IdUid(11, 9001407315212046187),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3438611402793041027),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2782422912130330068),
            name: 'deviceId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(2, 8913809777298525633)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2229372827153080958),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3255005315129367134),
            name: 'ipAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4214378585471904764),
            name: 'port',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7972253737087714770),
            name: 'type',
            type: 2,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4121618874255560041),
            name: 'isConnected',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2894600900195736610),
            name: 'lastSyncTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2282712074892714099),
            name: 'publicKey',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5963359043766204767),
            name: 'discoveredAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 9001407315212046187),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 4533602116414280180),
      name: 'ReminderModel',
      lastPropertyId: const obx_int.IdUid(10, 5647762335693606511),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8630018029222799010),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2009264891271904392),
            name: 'reminderId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 4592552275713327524)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 355010567260314261),
            name: 'scheduleId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 8568316965518355834),
            relationTarget: 'ScheduleModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1823656816091319605),
            name: 'remindTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6289622672740199501),
            name: 'type',
            type: 2,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1753584450789914668),
            name: 'isTriggered',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 662899652753428028),
            name: 'minutesBefore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5677678857732848829),
            name: 'customMessage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1221993705972625907),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5647762335693606511),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 8036669778344400724),
      name: 'ReminderTemplateModel',
      lastPropertyId: const obx_int.IdUid(10, 45698094348914599),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3774224947580210741),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7391264039729391973),
            name: 'templateId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(5, 3982753243606089139)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2087230642354128135),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4556508213141085240),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8160594217564730927),
            name: 'minutesBefore',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5279031476445618960),
            name: 'type',
            type: 2,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5542896224568717962),
            name: 'customMessage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4978914809328735436),
            name: 'isDefault',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4980293587006764924),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 45698094348914599),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4984863835351113986),
      name: 'ScheduleModel',
      lastPropertyId: const obx_int.IdUid(15, 6006006967663797793),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7674266981860682102),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8078511232121078749),
            name: 'scheduleId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(6, 7034166725792878451)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7596952975789001204),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8612396065852059159),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6946689649467867132),
            name: 'startTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3013035726552366450),
            name: 'endTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1860097543820309386),
            name: 'location',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7215682736591290585),
            name: 'categoryId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3818300045862914051),
            name: 'priority',
            type: 2,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 127898755158210337),
            name: 'repeatRuleJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5415969423867699905),
            name: 'isCompleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6241634704323369474),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4135243250757084392),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4909588753892659321),
            name: 'deviceId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 6006006967663797793),
            name: 'syncHash',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'reminders', srcEntity: 'ReminderModel', srcField: 'schedule')
      ])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 4984863835351113986),
      lastIndexId: const obx_int.IdUid(6, 7034166725792878451),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryModel: obx_int.EntityDefinition<CategoryModel>(
        model: _entities[0],
        toOneRelations: (CategoryModel object) => [],
        toManyRelations: (CategoryModel object) => {},
        getId: (CategoryModel object) => object.id,
        setId: (CategoryModel object, int id) {
          object.id = id;
        },
        objectToFB: (CategoryModel object, fb.Builder fbb) {
          final categoryIdOffset = fbb.writeString(object.categoryId);
          final nameOffset = fbb.writeString(object.name);
          final colorOffset = fbb.writeString(object.color);
          final iconOffset = fbb.writeString(object.icon);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, colorOffset);
          fbb.addOffset(4, iconOffset);
          fbb.addBool(5, object.isDefault);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final categoryIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final colorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final iconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final isDefaultParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final object = CategoryModel(
              categoryId: categoryIdParam,
              name: nameParam,
              color: colorParam,
              icon: iconParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              isDefault: isDefaultParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    DeviceModel: obx_int.EntityDefinition<DeviceModel>(
        model: _entities[1],
        toOneRelations: (DeviceModel object) => [],
        toManyRelations: (DeviceModel object) => {},
        getId: (DeviceModel object) => object.id,
        setId: (DeviceModel object, int id) {
          object.id = id;
        },
        objectToFB: (DeviceModel object, fb.Builder fbb) {
          final deviceIdOffset = fbb.writeString(object.deviceId);
          final nameOffset = fbb.writeString(object.name);
          final ipAddressOffset = fbb.writeString(object.ipAddress);
          final publicKeyOffset = object.publicKey == null
              ? null
              : fbb.writeString(object.publicKey!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, deviceIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, ipAddressOffset);
          fbb.addInt64(4, object.port);
          fbb.addInt8(5, object.type);
          fbb.addBool(6, object.isConnected);
          fbb.addInt64(7, object.lastSyncTime?.millisecondsSinceEpoch);
          fbb.addOffset(8, publicKeyOffset);
          fbb.addInt64(9, object.discoveredAt.millisecondsSinceEpoch);
          fbb.addInt64(10, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastSyncTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final deviceIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final ipAddressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final portParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final typeParam =
              const fb.Int8Reader().vTableGet(buffer, rootOffset, 14, 0);
          final discoveredAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0));
          final isConnectedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final lastSyncTimeParam = lastSyncTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastSyncTimeValue);
          final publicKeyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final object = DeviceModel(
              deviceId: deviceIdParam,
              name: nameParam,
              ipAddress: ipAddressParam,
              port: portParam,
              type: typeParam,
              discoveredAt: discoveredAtParam,
              updatedAt: updatedAtParam,
              isConnected: isConnectedParam,
              lastSyncTime: lastSyncTimeParam,
              publicKey: publicKeyParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ReminderModel: obx_int.EntityDefinition<ReminderModel>(
        model: _entities[2],
        toOneRelations: (ReminderModel object) => [object.schedule],
        toManyRelations: (ReminderModel object) => {},
        getId: (ReminderModel object) => object.id,
        setId: (ReminderModel object, int id) {
          object.id = id;
        },
        objectToFB: (ReminderModel object, fb.Builder fbb) {
          final reminderIdOffset = fbb.writeString(object.reminderId);
          final customMessageOffset = object.customMessage == null
              ? null
              : fbb.writeString(object.customMessage!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, reminderIdOffset);
          fbb.addInt64(2, object.schedule.targetId);
          fbb.addInt64(3, object.remindTime.millisecondsSinceEpoch);
          fbb.addInt8(4, object.type);
          fbb.addBool(5, object.isTriggered);
          fbb.addInt64(6, object.minutesBefore);
          fbb.addOffset(7, customMessageOffset);
          fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final reminderIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final remindTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final typeParam =
              const fb.Int8Reader().vTableGet(buffer, rootOffset, 12, 0);
          final minutesBeforeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));
          final isTriggeredParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final customMessageParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final object = ReminderModel(
              reminderId: reminderIdParam,
              remindTime: remindTimeParam,
              type: typeParam,
              minutesBefore: minutesBeforeParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              isTriggered: isTriggeredParam,
              customMessage: customMessageParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.schedule.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.schedule.attach(store);
          return object;
        }),
    ReminderTemplateModel: obx_int.EntityDefinition<ReminderTemplateModel>(
        model: _entities[3],
        toOneRelations: (ReminderTemplateModel object) => [],
        toManyRelations: (ReminderTemplateModel object) => {},
        getId: (ReminderTemplateModel object) => object.id,
        setId: (ReminderTemplateModel object, int id) {
          object.id = id;
        },
        objectToFB: (ReminderTemplateModel object, fb.Builder fbb) {
          final templateIdOffset = fbb.writeString(object.templateId);
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          final customMessageOffset = object.customMessage == null
              ? null
              : fbb.writeString(object.customMessage!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, templateIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.minutesBefore);
          fbb.addInt8(5, object.type);
          fbb.addOffset(6, customMessageOffset);
          fbb.addBool(7, object.isDefault);
          fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final templateIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final minutesBeforeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final typeParam =
              const fb.Int8Reader().vTableGet(buffer, rootOffset, 14, 0);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));
          final customMessageParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final isDefaultParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final object = ReminderTemplateModel(
              templateId: templateIdParam,
              name: nameParam,
              description: descriptionParam,
              minutesBefore: minutesBeforeParam,
              type: typeParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              customMessage: customMessageParam,
              isDefault: isDefaultParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ScheduleModel: obx_int.EntityDefinition<ScheduleModel>(
        model: _entities[4],
        toOneRelations: (ScheduleModel object) => [],
        toManyRelations: (ScheduleModel object) => {
              obx_int.RelInfo<ReminderModel>.toOneBacklink(3, object.id,
                      (ReminderModel srcObject) => srcObject.schedule):
                  object.reminders
            },
        getId: (ScheduleModel object) => object.id,
        setId: (ScheduleModel object, int id) {
          object.id = id;
        },
        objectToFB: (ScheduleModel object, fb.Builder fbb) {
          final scheduleIdOffset = fbb.writeString(object.scheduleId);
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final locationOffset = object.location == null
              ? null
              : fbb.writeString(object.location!);
          final categoryIdOffset = fbb.writeString(object.categoryId);
          final repeatRuleJsonOffset = object.repeatRuleJson == null
              ? null
              : fbb.writeString(object.repeatRuleJson!);
          final deviceIdOffset = object.deviceId == null
              ? null
              : fbb.writeString(object.deviceId!);
          final syncHashOffset = object.syncHash == null
              ? null
              : fbb.writeString(object.syncHash!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, scheduleIdOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.startTime.millisecondsSinceEpoch);
          fbb.addInt64(5, object.endTime.millisecondsSinceEpoch);
          fbb.addOffset(6, locationOffset);
          fbb.addOffset(7, categoryIdOffset);
          fbb.addInt8(8, object.priority);
          fbb.addOffset(9, repeatRuleJsonOffset);
          fbb.addBool(10, object.isCompleted);
          fbb.addInt64(11, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(12, object.updatedAt.millisecondsSinceEpoch);
          fbb.addOffset(13, deviceIdOffset);
          fbb.addOffset(14, syncHashOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final scheduleIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final endTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final categoryIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final priorityParam =
              const fb.Int8Reader().vTableGet(buffer, rootOffset, 20, 0);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0));
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final locationParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final repeatRuleJsonParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final isCompletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false);
          final deviceIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final syncHashParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 32);
          final object = ScheduleModel(
              scheduleId: scheduleIdParam,
              title: titleParam,
              startTime: startTimeParam,
              endTime: endTimeParam,
              categoryId: categoryIdParam,
              priority: priorityParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              description: descriptionParam,
              location: locationParam,
              repeatRuleJson: repeatRuleJsonParam,
              isCompleted: isCompletedParam,
              deviceId: deviceIdParam,
              syncHash: syncHashParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<ScheduleModel>(
              object.reminders,
              store,
              obx_int.RelInfo<ReminderModel>.toOneBacklink(3, object.id,
                  (ReminderModel srcObject) => srcObject.schedule));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryModel] entity fields to define ObjectBox queries.
class CategoryModel_ {
  /// see [CategoryModel.id]
  static final id =
      obx.QueryIntegerProperty<CategoryModel>(_entities[0].properties[0]);

  /// see [CategoryModel.categoryId]
  static final categoryId =
      obx.QueryStringProperty<CategoryModel>(_entities[0].properties[1]);

  /// see [CategoryModel.name]
  static final name =
      obx.QueryStringProperty<CategoryModel>(_entities[0].properties[2]);

  /// see [CategoryModel.color]
  static final color =
      obx.QueryStringProperty<CategoryModel>(_entities[0].properties[3]);

  /// see [CategoryModel.icon]
  static final icon =
      obx.QueryStringProperty<CategoryModel>(_entities[0].properties[4]);

  /// see [CategoryModel.isDefault]
  static final isDefault =
      obx.QueryBooleanProperty<CategoryModel>(_entities[0].properties[5]);

  /// see [CategoryModel.createdAt]
  static final createdAt =
      obx.QueryDateProperty<CategoryModel>(_entities[0].properties[6]);

  /// see [CategoryModel.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<CategoryModel>(_entities[0].properties[7]);
}

/// [DeviceModel] entity fields to define ObjectBox queries.
class DeviceModel_ {
  /// see [DeviceModel.id]
  static final id =
      obx.QueryIntegerProperty<DeviceModel>(_entities[1].properties[0]);

  /// see [DeviceModel.deviceId]
  static final deviceId =
      obx.QueryStringProperty<DeviceModel>(_entities[1].properties[1]);

  /// see [DeviceModel.name]
  static final name =
      obx.QueryStringProperty<DeviceModel>(_entities[1].properties[2]);

  /// see [DeviceModel.ipAddress]
  static final ipAddress =
      obx.QueryStringProperty<DeviceModel>(_entities[1].properties[3]);

  /// see [DeviceModel.port]
  static final port =
      obx.QueryIntegerProperty<DeviceModel>(_entities[1].properties[4]);

  /// see [DeviceModel.type]
  static final type =
      obx.QueryIntegerProperty<DeviceModel>(_entities[1].properties[5]);

  /// see [DeviceModel.isConnected]
  static final isConnected =
      obx.QueryBooleanProperty<DeviceModel>(_entities[1].properties[6]);

  /// see [DeviceModel.lastSyncTime]
  static final lastSyncTime =
      obx.QueryDateProperty<DeviceModel>(_entities[1].properties[7]);

  /// see [DeviceModel.publicKey]
  static final publicKey =
      obx.QueryStringProperty<DeviceModel>(_entities[1].properties[8]);

  /// see [DeviceModel.discoveredAt]
  static final discoveredAt =
      obx.QueryDateProperty<DeviceModel>(_entities[1].properties[9]);

  /// see [DeviceModel.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<DeviceModel>(_entities[1].properties[10]);
}

/// [ReminderModel] entity fields to define ObjectBox queries.
class ReminderModel_ {
  /// see [ReminderModel.id]
  static final id =
      obx.QueryIntegerProperty<ReminderModel>(_entities[2].properties[0]);

  /// see [ReminderModel.reminderId]
  static final reminderId =
      obx.QueryStringProperty<ReminderModel>(_entities[2].properties[1]);

  /// see [ReminderModel.schedule]
  static final schedule = obx.QueryRelationToOne<ReminderModel, ScheduleModel>(
      _entities[2].properties[2]);

  /// see [ReminderModel.remindTime]
  static final remindTime =
      obx.QueryDateProperty<ReminderModel>(_entities[2].properties[3]);

  /// see [ReminderModel.type]
  static final type =
      obx.QueryIntegerProperty<ReminderModel>(_entities[2].properties[4]);

  /// see [ReminderModel.isTriggered]
  static final isTriggered =
      obx.QueryBooleanProperty<ReminderModel>(_entities[2].properties[5]);

  /// see [ReminderModel.minutesBefore]
  static final minutesBefore =
      obx.QueryIntegerProperty<ReminderModel>(_entities[2].properties[6]);

  /// see [ReminderModel.customMessage]
  static final customMessage =
      obx.QueryStringProperty<ReminderModel>(_entities[2].properties[7]);

  /// see [ReminderModel.createdAt]
  static final createdAt =
      obx.QueryDateProperty<ReminderModel>(_entities[2].properties[8]);

  /// see [ReminderModel.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<ReminderModel>(_entities[2].properties[9]);
}

/// [ReminderTemplateModel] entity fields to define ObjectBox queries.
class ReminderTemplateModel_ {
  /// see [ReminderTemplateModel.id]
  static final id = obx.QueryIntegerProperty<ReminderTemplateModel>(
      _entities[3].properties[0]);

  /// see [ReminderTemplateModel.templateId]
  static final templateId = obx.QueryStringProperty<ReminderTemplateModel>(
      _entities[3].properties[1]);

  /// see [ReminderTemplateModel.name]
  static final name = obx.QueryStringProperty<ReminderTemplateModel>(
      _entities[3].properties[2]);

  /// see [ReminderTemplateModel.description]
  static final description = obx.QueryStringProperty<ReminderTemplateModel>(
      _entities[3].properties[3]);

  /// see [ReminderTemplateModel.minutesBefore]
  static final minutesBefore = obx.QueryIntegerProperty<ReminderTemplateModel>(
      _entities[3].properties[4]);

  /// see [ReminderTemplateModel.type]
  static final type = obx.QueryIntegerProperty<ReminderTemplateModel>(
      _entities[3].properties[5]);

  /// see [ReminderTemplateModel.customMessage]
  static final customMessage = obx.QueryStringProperty<ReminderTemplateModel>(
      _entities[3].properties[6]);

  /// see [ReminderTemplateModel.isDefault]
  static final isDefault = obx.QueryBooleanProperty<ReminderTemplateModel>(
      _entities[3].properties[7]);

  /// see [ReminderTemplateModel.createdAt]
  static final createdAt =
      obx.QueryDateProperty<ReminderTemplateModel>(_entities[3].properties[8]);

  /// see [ReminderTemplateModel.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<ReminderTemplateModel>(_entities[3].properties[9]);
}

/// [ScheduleModel] entity fields to define ObjectBox queries.
class ScheduleModel_ {
  /// see [ScheduleModel.id]
  static final id =
      obx.QueryIntegerProperty<ScheduleModel>(_entities[4].properties[0]);

  /// see [ScheduleModel.scheduleId]
  static final scheduleId =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[1]);

  /// see [ScheduleModel.title]
  static final title =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[2]);

  /// see [ScheduleModel.description]
  static final description =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[3]);

  /// see [ScheduleModel.startTime]
  static final startTime =
      obx.QueryDateProperty<ScheduleModel>(_entities[4].properties[4]);

  /// see [ScheduleModel.endTime]
  static final endTime =
      obx.QueryDateProperty<ScheduleModel>(_entities[4].properties[5]);

  /// see [ScheduleModel.location]
  static final location =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[6]);

  /// see [ScheduleModel.categoryId]
  static final categoryId =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[7]);

  /// see [ScheduleModel.priority]
  static final priority =
      obx.QueryIntegerProperty<ScheduleModel>(_entities[4].properties[8]);

  /// see [ScheduleModel.repeatRuleJson]
  static final repeatRuleJson =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[9]);

  /// see [ScheduleModel.isCompleted]
  static final isCompleted =
      obx.QueryBooleanProperty<ScheduleModel>(_entities[4].properties[10]);

  /// see [ScheduleModel.createdAt]
  static final createdAt =
      obx.QueryDateProperty<ScheduleModel>(_entities[4].properties[11]);

  /// see [ScheduleModel.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<ScheduleModel>(_entities[4].properties[12]);

  /// see [ScheduleModel.deviceId]
  static final deviceId =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[13]);

  /// see [ScheduleModel.syncHash]
  static final syncHash =
      obx.QueryStringProperty<ScheduleModel>(_entities[4].properties[14]);

  /// see [ScheduleModel.reminders]
  static final reminders =
      obx.QueryBacklinkToMany<ReminderModel, ScheduleModel>(
          ReminderModel_.schedule);
}
